### ISSUE TITLE
Removing unnecessary files ?

### ISSUE THREAD

**Issue by gbraad** [crc-org/crc-github-action#15]
This is not the responsibility of this action:

https://github.com/crc-org/crc-github-action/blob/e1ca5b17649dee40a753afe89b476ad0cfa4d1ff/action.yml#L84

This can be handled by a public marketplace solution. This can have unforeseen side-effects for the workflow owner, like unable to compile code (haskell, dotnet, etc) on the runner.

---

Make this the responsibility of the workflow owner, as the disk layout of these runners can differ and change over time. https://github.com/easimon/maximize-build-space/issues/48

I moved the cleanup from the `action.yml` to the test.
```yaml
      - name: Remove unwanted stuff to free up disk image
        shell: bash
        run: |
          sudo rm -rf /usr/share/dotnet
          sudo rm -rf /usr/local/lib/android
          sudo rm -rf /opt/ghc
          sudo rm -rf "/usr/local/share/boost"
          sudo rm -rf /opt/hostedtoolcache/CodeQL
  
          sudo docker image prune --all --force

          sudo swapoff -a
          sudo rm -f /mnt/swapfile
```

**Comment by gbraad** [comment]
```yaml
      - name: Maximize build space
        uses: AdityaGarg8/remove-unwanted-software@v4.1
        with:
          remove-dotnet: true
          remove-android: true
          remove-haskell: true
          remove-codeql: true
          remove-docker-images: true
          remove-large-packages: true
          remove-cached-tools: true
          remove-swapfile: true
```

This one works
